name: Train and Evaluate MLP Model

on:
  workflow_dispatch:
    inputs:
      run_train:
        description: 'Czy trenować model?'
        required: true
        default: 'yes'
      run_eval:
        description: 'Czy ewaluować model?'
        required: true
        default: 'yes'

jobs:
  train:
    if: ${{ github.event.inputs.run_train == 'yes' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install datasets scikit-learn joblib

      - name: Train model
        run: |
          python train.py

  evaluate:
    if: ${{ github.event.inputs.run_eval == 'yes' }}
    runs-on: ubuntu-latest
    needs: train
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install datasets scikit-learn joblib pandas

      - name: Run evaluation
        run: |
          python evaluate.py